name: Strategy Testing Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install weasyprint streamlit matplotlib pandas scikit-learn jinja2

    - name: Run full pipeline
      run: |
        python PythonCore/pipeline.py --num_strategies 500 --symbol EURUSD --data Data/EURUSD_M1.csv

    - name: Upload reports as artifact
      uses: actions/upload-artifact@v3
      with:
        name: strategy-reports
        path: |
          Reports/final_report.html
          Reports/final_report.pdf
          Reports/*.png

    - name: Deploy to GitHub Pages (optional)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Reports
